version: '2'
services:
    unlimitedvoucher-app:
        image: unlimitedvoucher
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://unlimitedvoucher-mysql:3306/unlimitedvoucher?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    unlimitedvoucher-mysql:
        extends:
            file: mysql.yml
            service: unlimitedvoucher-mysql
